import { pgTable, text, timestamp, uuid } from "drizzle-orm/pg-core";

export const users = pgTable("user", {
	id: text("id").primaryKey(),
	name: text("name").notNull(),
	email: text("email").notNull().unique(),
	emailVerified: timestamp("email_verified"),
	image: text("image"),
	createdAt: timestamp("created_at").notNull().defaultNow(),
	updatedAt: timestamp("updated_at").notNull().defaultNow(),
});

export const sessions = pgTable("session", {
	id: text("id").primaryKey(),
	expiresAt: timestamp("expires_at").notNull(),
	token: text("token").notNull().unique(),
	createdAt: timestamp("created_at").notNull().defaultNow(),
	updatedAt: timestamp("updated_at").notNull().defaultNow(),
	ipAddress: text("ip_address"),
	userAgent: text("user_agent"),
	userId: text("user_id")
		.notNull()
		.references(() => users.id),
});

export const accounts = pgTable("account", {
	id: text("id").primaryKey(),
	accountId: text("account_id").notNull(),
	providerId: text("provider_id").notNull(),
	userId: text("user_id")
		.notNull()
		.references(() => users.id),
	accessToken: text("access_token"),
	refreshToken: text("refresh_token"),
	idToken: text("id_token"),
	accessTokenExpiresAt: timestamp("access_token_expires_at"),
	refreshTokenExpiresAt: timestamp("refresh_token_expires_at"),
	scope: text("scope"),
	password: text("password"),
	createdAt: timestamp("created_at").notNull().defaultNow(),
	updatedAt: timestamp("updated_at").notNull().defaultNow(),
});

export const verifications = pgTable("verification", {
	id: text("id").primaryKey(),
	identifier: text("identifier").notNull(),
	value: text("value").notNull(),
	expiresAt: timestamp("expires_at").notNull(),
	createdAt: timestamp("created_at"),
	updatedAt: timestamp("updated_at"),
});

export const orders = pgTable("order", {
	id: text("id").primaryKey(), // Usually generated by our system, starts with 'ord_' etc.
	gatewayOrderId: text("gateway_order_id"), // Order ID returned by the payment gateway
	amount: text("amount").notNull(), // Amount in cents or yuan
	status: text("status").notNull().default("pending"), // pending, paid, failed, refunded
	articleId: text("article_id").notNull(), // Matches the slug or ID of the markdown file
	userId: text("user_id").references(() => users.id), // Optional, if user is logged in
	guestEmail: text("guest_email"), // Optional, if guest checkout
	sessionId: text("session_id"), // Strongly links a guest order to their current browser session
	payUrl: text("pay_url"), // URL/QR code data for the payment
	gatewayData: text("gateway_data"), // JSON string to store unstructured data from gateway
	createdAt: timestamp("created_at").notNull().defaultNow(),
	paidAt: timestamp("paid_at"),
	updatedAt: timestamp("updated_at").notNull().defaultNow(),
});
